// Project: libv.control, Created on 2020.03.16. 16:41, Author: Császár Mátyás [Vader]

#pragma once

// ext
#include <boost/container/flat_set.hpp>
// std
#include <vector>
// pro
#include <libv/ctrl/binding.hpp>
#include <libv/ctrl/scale.hpp>


namespace libv {
namespace ctrl {

// -------------------------------------------------------------------------------------------------

//struct ActiveBinding {
//	const Binding* ptr;
//	scale_type scale;
//};
//
//struct Bindings {
//	std::vector<std::unique_ptr<Binding>> bindings;
//	boost::container::flat_set<ActiveBinding> active_bindings;
//};

// -------------------------------------------------------------------------------------------------

} // namespace ctrl
} // namespace libv
