// Project: libv.ui, File: src/libv/ui/overlay_zoom.lpp, Author: Császár Mátyás [Vader]

#pragma once

// libv
#include <libv/math/vec.hpp>
// pro
#include <libv/ui/component.hpp>
#include <libv/ui/event_host.hpp>


namespace libv {
namespace ui {

// -------------------------------------------------------------------------------------------------

enum class OverlayZoomMode {
	disabled,
	control,
	view,
};

class OverlayZoom : public ComponentHandler<class CoreOverlayZoom, EventHostGeneral<OverlayZoom>> {
public:
	explicit OverlayZoom(std::string name);
	explicit OverlayZoom(GenerateName_t = {}, const std::string_view type = "overlay-zoom");
	explicit OverlayZoom(core_ptr core) noexcept;

public:
	void control();
	void view();
	void disable();

public:
	[[nodiscard]] libv::vec2f screen_BL() const;
	[[nodiscard]] libv::vec2f screen_TR() const;

public:
	void postRender(class Renderer& r);
};

// -------------------------------------------------------------------------------------------------

} // namespace ui
} // namespace libv
