// Project: libv.serial, File: src/libv/serial/enable.hpp

#pragma once


#define LIBV_SERIALIZATION_ENABLE_REFLECTION_SAVE() using __libv_SERIALIZATION_enable_reflection_save = void
#define LIBV_SERIALIZATION_ENABLE_REFLECTION_LOAD() using __libv_SERIALIZATION_enable_reflection_load = void
#define LIBV_SERIALIZATION_ENABLE_REFLECTION() LIBV_SERIALIZATION_ENABLE_REFLECTION_SAVE(); LIBV_SERIALIZATION_ENABLE_REFLECTION_LOAD()

#define LIBV_SERIALIZATION_ENABLE_MEMBERWISE_SAVE() using __libv_SERIALIZATION_enable_memberwise_save = void
#define LIBV_SERIALIZATION_ENABLE_MEMBERWISE_LOAD() using __libv_SERIALIZATION_enable_memberwise_load = void
#define LIBV_SERIALIZATION_ENABLE_MEMBERWISE() LIBV_SERIALIZATION_ENABLE_MEMBERWISE_SAVE(); LIBV_SERIALIZATION_ENABLE_MEMBERWISE_LOAD()
